# Generated by Django 5.0.1 on 2024-02-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_construct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_construct.post'),
        ),
    ]
